function startGame() {
document.getElementById("start-screen").style.display = "none";
randomRight();
document.getElementById("game-screen").style.display = "block";
setInterval(counting,1000);
}
// used for starting game and showing it ^

function randNum(){
  return (Math.floor(Math.random() * Math.floor(4)))+1;
}
// used for randomizing the right choice ^

let i=1;
let rightChoice = 1;
let score = 0;
let x = 0;
let hypeLevel = 0;

function counting() { 
if (i<200){
document.getElementById("timeProgressLeftShowing").style.height = "calc(" + i/2 + "%)";
  i++;
  }
  else {
    document.getElementById("game-screen").style.display = "none";
    winScreen();
    document.getElementById("finish-screen").style.display = "block";
  }
}
// counting the time and checking if it is already reached its end ^

function clicked() {
  if (i<180){
    i+=20;
    document.getElementById("game-clue").innerHTML = i;
  }
}
// used for checking outcomes ^

function randomRight() {
  x = randNum();
      document.getElementById("game-clue").innerHTML = x;
  
  let y = (Math.floor(Math.random() * Math.floor(169)));
  // number of questions avialable ^


  // placing the correct question in right position
  if (x === 1) {
    document.getElementById("game-clue").innerHTML = questions[y].question;
    document.getElementById("pick1").style.backgroundImage = "url("+questions[y].good1+")";
    document.getElementById("pick2").style.backgroundImage = "url("+questions[y].bad1+")";
    document.getElementById("pick3").style.backgroundImage = "url("+questions[y].bad2+")";
    document.getElementById("pick4").style.backgroundImage = "url("+questions[y].bad3+")";
}   else if (x === 2) {
    document.getElementById("game-clue").innerHTML = questions[y].question;
    document.getElementById("pick1").style.backgroundImage = "url("+questions[y].bad1+")";
    document.getElementById("pick2").style.backgroundImage = "url("+questions[y].good1+")";
    document.getElementById("pick3").style.backgroundImage = "url("+questions[y].bad2+")";
    document.getElementById("pick4").style.backgroundImage = "url("+questions[y].bad3+")";
}   else if (x === 3) {
    document.getElementById("game-clue").innerHTML = questions[y].question;
    document.getElementById("pick1").style.backgroundImage = "url("+questions[y].bad1+")";
    document.getElementById("pick2").style.backgroundImage = "url("+questions[y].bad2+")";
    document.getElementById("pick3").style.backgroundImage = "url("+questions[y].good1+")";
    document.getElementById("pick4").style.backgroundImage = "url("+questions[y].bad3+")";
}   else if (x === 4) {
    document.getElementById("game-clue").innerHTML = questions[y].question;
    document.getElementById("pick1").style.backgroundImage = "url("+questions[y].bad1+")";
    document.getElementById("pick2").style.backgroundImage = "url("+questions[y].bad2+")";
    document.getElementById("pick3").style.backgroundImage = "url("+questions[y].bad3+")";
    document.getElementById("pick4").style.backgroundImage = "url("+questions[y].good1+")";
}

}

function checkRight(c) {
    // if score is right the if statement is checking how much points it needs to add
    if(c===x){
        score++;
        hypeLevel++;
        if (hypeLevel < 6) {
            document.getElementById("game-points").innerHTML = "Additional point! [ "+score+" ⭐️]";
            document.getElementById("scoreProgressLeftShowing").style.height = 100 - hypeLevel*8 +"%";
        } else {
            score++;
            if (hypeLevel < 10) {
                document.getElementById("game-points").innerHTML = "2x points! 🔥 [ "+score+" ⭐️]";
                document.getElementById("scoreProgressLeftShowing").style.height = 100 - hypeLevel*10 +"%";
            } else {
                score++;
                document.getElementById("game-points").innerHTML = "3x points! 🔥🔥 [ "+score+" ⭐️]";
                document.getElementById("scoreProgressLeftShowing").style.height = "0%";
            }
        }
    } else {
        // if you click the wrong one
        i++;
        hypeLevel = 0;
        document.getElementById("game-points").innerHTML = "You missed and lost 1 second from your time!";
        document.getElementById("scoreProgressLeftShowing").style.height = "100%";
    }


    randomRight();
    // checkHypeLevel();
}

// function checkHypeLevel(){
//     if (hypeLevel==)
// }

function winScreen() {
    let winValue = (Math.floor(Math.random() * Math.floor(9)));
    document.getElementById("game-points").innerHTML = "Your final score equals [ "+score+" ⭐️]";
    if (score <= 50){
        document.getElementById("game-clue").innerHTML = "You are best as a dead man!";
        document.getElementById("finish-screen-outline").style.backgroundImage = "url(https://heroes.thelazy.net/images/1/10/Creature_Peasant.gif)";
    } else if (50 <= score && score <= 100) {
        document.getElementById("game-clue").innerHTML = "You are at least worth 35 coins!";
        document.getElementById("finish-screen-outline").style.backgroundImage = "url(https://heroes.thelazy.net/images/2/21/Creature_Nymph.gif)";
    } else if (100 <= score && score <= 150) {
        document.getElementById("game-clue").innerHTML = "You are a nice mate! Crew mate!";
        document.getElementById("finish-screen-outline").style.backgroundImage = "url(https://heroes.thelazy.net/images/9/98/Creature_Crew_Mate.gif)";
    } else if (150 <= score && score <= 200) {
        document.getElementById("game-clue").innerHTML = "You feel strange urge to look into mirror and yell JACK SPARROW!";
        document.getElementById("finish-screen-outline").style.backgroundImage = "url(https://heroes.thelazy.net/images/4/43/Creature_Pirate.gif)";
    } else if (200 <= score && score <= 250) {
        document.getElementById("game-clue").innerHTML = "Finest on the plate, but knows how to fight too!";
        document.getElementById("finish-screen-outline").style.backgroundImage = "url(https://heroes.thelazy.net/images/b/b8/Creature_Stormbird.gif)";
    } else if (250 <= score && score <= 300) {
        document.getElementById("game-clue").innerHTML = "Like to spend time next to sea and beach! I am sea witch! SEA WITCH!";
        document.getElementById("finish-screen-outline").style.backgroundImage = "url(https://heroes.thelazy.net/images/0/01/Creature_Sea_Witch.gif)";
    } else if (300 <= score && score <= 350) {
        document.getElementById("game-clue").innerHTML = "At last you have nice personality!";
        document.getElementById("finish-screen-outline").style.backgroundImage = "url(https://heroes.thelazy.net/images/b/b2/Creature_Nix.gif)";
    } else {
        document.getElementById("game-clue").innerHTML = "You are a cute addition to Triton pleasure basement!";
        document.getElementById("finish-screen-outline").style.backgroundImage = "url(https://heroes.thelazy.net/images/5/5c/Creature_Sea_Serpent.gif)";
    }
}

var questions = [
{question:"Which hero has speciality in gold?", good1:"https://heroes.thelazy.net/images/1/1f/Hero_Jenova_small.gif", bad1:"https://heroes.thelazy.net/images/6/61/Hero_Elleshar_small.gif", bad2:"https://heroes.thelazy.net/images/6/6b/Hero_Josephine_small.gif", bad3:"https://heroes.thelazy.net/images/a/a9/Hero_Melodia_small.gif"}, 
{question:"Which spell is from air magic?", good1:"https://heroes.thelazy.net/images/e/e1/Air_Shield_small.png", bad1:"https://heroes.thelazy.net/images/2/2a/Weakness_small.png", bad2:"https://heroes.thelazy.net/images/b/b6/Visions_small.png", bad3:"https://heroes.thelazy.net/images/3/32/Quicksand_small.png"},
{question: "Which spell is from level I?", good1: "https://heroes.thelazy.net/images/3/3d/Dispel_small.png", bad1: "https://heroes.thelazy.net/images/f/fe/Death_Ripple_small.png", bad2: "https://heroes.thelazy.net/images/a/ab/Disguise_small.png", bad3: "https://heroes.thelazy.net/images/c/cc/Fire_Wall_small.png"},
{question: "Which spell is from level II?", good1: "https://heroes.thelazy.net/images/d/d3/Fortune_small.png", bad1: "https://heroes.thelazy.net/images/e/e1/Air_Shield_small.png", bad2: "https://heroes.thelazy.net/images/3/36/Summon_Boat_small.png", bad3: "https://heroes.thelazy.net/images/4/45/Protection_from_Water_small.png"},
{question: "Which spell is from level III?", good1: "https://heroes.thelazy.net/images/6/68/Land_Mine_small.png", bad1: "https://heroes.thelazy.net/images/a/a0/Clone_small.png", bad2: "https://heroes.thelazy.net/images/0/00/Remove_Obstacle_small.png", bad3: "https://heroes.thelazy.net/images/a/a0/Scuttle_Boat_small.png"},
{question: "Which spell is from level IV?", good1: "https://heroes.thelazy.net/images/d/d5/Slayer_small.png", bad1: "https://heroes.thelazy.net/images/9/96/Dimension_Door_small.png", bad2: "https://heroes.thelazy.net/images/1/10/Magic_Mirror_small.png", bad3: "https://heroes.thelazy.net/images/c/cf/Summon_Water_Elemental_small.png"},
{question: "Which spell is from level V?", good1: "https://heroes.thelazy.net/images/7/70/Sacrifice_small.png", bad1: "https://heroes.thelazy.net/images/f/f2/Water_Walk_small.png", bad2: "https://heroes.thelazy.net/images/0/0f/Town_Portal_small.png", bad3: "https://heroes.thelazy.net/images/9/9b/Teleport_small.png"},
{question: "Which city is the most recent one?", good1: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif", bad1: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/8/83/Adventure_Map_Stronghold_fort.gif"},
{question: "Which creature is upgraded version?", good1: "https://heroes.thelazy.net/images/d/d8/Creature_Dragon_Fly.gif", bad1: "https://heroes.thelazy.net/images/c/cd/Creature_Wyvern.gif", bad2: "https://heroes.thelazy.net/images/f/f1/Creature_Pit_Fiend.gif", bad3: "https://heroes.thelazy.net/images/8/86/Creature_Gremlin.gif"},
{question: "Which artifact produces 1 unit of gems per day?", good1: "https://heroes.thelazy.net/images/e/e4/Artifact_Ring_of_Infinite_Gems.gif", bad1: "https://heroes.thelazy.net/images/6/6a/Artifact_Cornucopia.gif", bad2: "https://heroes.thelazy.net/images/2/21/Artifact_Everflowing_Crystal_Cloak.gif", bad3: "https://heroes.thelazy.net/images/f/fd/Artifact_Eversmoking_Ring_of_Sulfur.gif"},
{question: "Quick! Kill the cucumber!", good1: "https://heroes.thelazy.net/images/c/c1/Creature_Troglodyte.gif", bad1: "https://heroes.thelazy.net/images/f/fd/Creature_Red_Dragon.gif", bad2: "https://heroes.thelazy.net/images/b/b8/Creature_Walking_Dead.gif", bad3: "https://heroes.thelazy.net/images/5/57/Creature_Lich.gif"},
{question: "Click the one with highest chances to get raped!", good1: "https://heroes.thelazy.net/images/a/a9/Creature_Pixie.gif", bad1: "https://heroes.thelazy.net/images/7/76/Creature_Phoenix.gif", bad2: "https://heroes.thelazy.net/images/6/64/Creature_Air_Elemental.gif", bad3: "https://heroes.thelazy.net/images/6/6d/Creature_Psychic_Elemental.gif"},
{question: "Click the goodest boi!", good1: "https://heroes.thelazy.net/images/0/07/Creature_Mighty_Gorgon.gif", bad1: "https://heroes.thelazy.net/images/5/59/Creature_Gorgon.gif", bad2: "https://heroes.thelazy.net/images/5/59/Creature_Gorgon.gif", bad3: "https://heroes.thelazy.net/images/5/59/Creature_Gorgon.gif"},
{question: "Kill the retarded machine!", good1: "https://heroes.thelazy.net/images/7/79/Creature_Angel.gif", bad1: "https://heroes.thelazy.net/images/a/a8/Creature_Gnoll.gif", bad2: "https://heroes.thelazy.net/images/a/a8/Creature_Gnoll.gif", bad3: "https://heroes.thelazy.net/images/a/a8/Creature_Gnoll.gif"},
{question: "Kill the one who shoots using his kidney stones!", good1: "https://heroes.thelazy.net/images/1/11/Creature_Cyclops_King.gif", bad1: "https://heroes.thelazy.net/images/8/81/Creature_Roc.gif", bad2: "https://heroes.thelazy.net/images/9/93/Creature_Behemoth.gif", bad3: "https://heroes.thelazy.net/images/a/a8/Creature_Ogre.gif"},
{question: "Kill the Gelu dungeon slave!", good1: "https://heroes.thelazy.net/images/d/d3/Creature_Sharpshooter.gif", bad1: "https://heroes.thelazy.net/images/7/7e/Creature_Mummy.gif", bad2: "https://heroes.thelazy.net/images/0/0b/Creature_Troll.gif", bad3: "https://heroes.thelazy.net/images/9/92/Creature_Nomad.gif"},
{question: "Kill the random idiot with friendly fire enabled!", good1: "https://heroes.thelazy.net/images/3/3c/Creature_Faerie_Dragon.gif", bad1: "https://heroes.thelazy.net/images/7/7e/Creature_Mummy.gif", bad2: "https://heroes.thelazy.net/images/4/4f/Creature_Gold_Golem.gif", bad3: "https://heroes.thelazy.net/images/c/cd/Creature_Halfling.gif"},
{question: "Kill the best walking skeleton candidate!", good1: "https://heroes.thelazy.net/images/1/10/Creature_Peasant.gif", bad1: "https://heroes.thelazy.net/images/0/05/Creature_Satyr.gif", bad2: "https://heroes.thelazy.net/images/5/50/Creature_Rust_Dragon.gif", bad3: "https://heroes.thelazy.net/images/9/9a/Creature_Diamondgolem.gif"},
{question: "... Cthulu? Master?", good1: "https://heroes.thelazy.net/images/8/89/Creature_Fangarm.gif", bad1: "https://heroes.thelazy.net/images/2/2b/Creature_Rogue.gif", bad2: "https://heroes.thelazy.net/images/2/2b/Creature_Rogue.gif", bad3: "https://heroes.thelazy.net/images/2/2b/Creature_Rogue.gif"},
{question: "R O B O C O P", good1: "https://heroes.thelazy.net/images/a/a2/SteelgolemStill.gif", bad1: "https://heroes.thelazy.net/images/1/10/Creature_Peasant.gif", bad2: "https://heroes.thelazy.net/images/1/10/Creature_Peasant.gif", bad3: "https://heroes.thelazy.net/images/1/10/Creature_Peasant.gif"},
{question: "Click the slowest one!", good1: "https://heroes.thelazy.net/images/6/64/Creature_Dendroid_Guard.gif", bad1: "https://heroes.thelazy.net/images/5/50/Creature_Battle_Dwarf.gif", bad2: "https://heroes.thelazy.net/images/7/73/Creature_Zombie.gif", bad3: "https://heroes.thelazy.net/images/a/a0/Creature_Basilisk.gif"},
{question: "Click the one that produces hydras!", good1: "https://heroes.thelazy.net/images/b/b3/Hydra_Pond-dwelling.gif", bad1: "https://heroes.thelazy.net/images/2/20/Lizard_Den-dwelling.gif", bad2: "https://heroes.thelazy.net/images/0/00/Basilisk_Pit-dwelling.gif", bad3: "https://heroes.thelazy.net/images/9/9d/Serpent_Fly_Hive-dwelling.gif"},
{question: "Click the attack icon!", good1: "https://heroes.thelazy.net/images/6/6f/Attack_skill.png", bad1: "https://heroes.thelazy.net/images/7/7b/Defense_skill.png", bad2: "https://heroes.thelazy.net/images/e/e0/Power_skill.png", bad3: "https://heroes.thelazy.net/images/9/90/Knowledge_skill.png"},
{question: "Click the knowledge icon!", good1: "https://heroes.thelazy.net/images/9/90/Knowledge_skill.png", bad1: "https://heroes.thelazy.net/images/e/e0/Power_skill.png", bad2: "https://heroes.thelazy.net/images/7/7b/Defense_skill.png", bad3: "https://heroes.thelazy.net/images/6/6f/Attack_skill.png"},
{question: "Click the power icon!", good1: "https://heroes.thelazy.net/images/e/e0/Power_skill.png", bad1: "https://heroes.thelazy.net/images/7/7b/Defense_skill.png", bad2: "https://heroes.thelazy.net/images/6/6f/Attack_skill.png", bad3: "https://heroes.thelazy.net/images/9/90/Knowledge_skill.png"},
{question: "Click the defense icon!", good1: "https://heroes.thelazy.net/images/7/7b/Defense_skill.png", bad1: "https://heroes.thelazy.net/images/6/6f/Attack_skill.png", bad2: "https://heroes.thelazy.net/images/e/e0/Power_skill.png", bad3: "https://heroes.thelazy.net/images/9/90/Knowledge_skill.png"},
{question: "Click the Abandoned Mine!", good1: "https://heroes.thelazy.net/images/9/98/Abandoned_Mine_4.gif", bad1: "https://heroes.thelazy.net/images/9/9d/Black_Tower_2in1.gif", bad2: "https://heroes.thelazy.net/images/4/41/Altar_of_Mana.gif", bad3: "https://heroes.thelazy.net/images/0/0c/Black_Market.gif"},
{question: "Click the Alchemist's Lab!", good1: "https://heroes.thelazy.net/images/a/a1/Alchemist%27s_Lab.gif", bad1: "https://heroes.thelazy.net/images/9/98/Abandoned_Mine_4.gif", bad2: "https://heroes.thelazy.net/images/9/9d/Black_Tower_2in1.gif", bad3: "https://heroes.thelazy.net/images/4/41/Altar_of_Mana.gif"},
{question: "Click the Altar Of Mana!", good1: "https://heroes.thelazy.net/images/4/41/Altar_of_Mana.gif", bad1: "https://heroes.thelazy.net/images/9/98/Abandoned_Mine_4.gif", bad2: "https://heroes.thelazy.net/images/a/a1/Alchemist%27s_Lab.gif", bad3: "https://heroes.thelazy.net/images/2/24/Altar_of_Sacrifice.gif"},
{question: "Click the Altar Of Sacrifice!", good1: "https://heroes.thelazy.net/images/2/24/Altar_of_Sacrifice.gif", bad1: "https://heroes.thelazy.net/images/9/98/Abandoned_Mine_4.gif", bad2: "https://heroes.thelazy.net/images/a/a1/Alchemist%27s_Lab.gif", bad3: "https://heroes.thelazy.net/images/4/41/Altar_of_Mana.gif"},
{question: "Click the Ancient lamp!", good1: "https://heroes.thelazy.net/images/6/6d/Ancient_Lamp.gif", bad1: "https://heroes.thelazy.net/images/9/98/Abandoned_Mine_4.gif", bad2: "https://heroes.thelazy.net/images/a/a1/Alchemist%27s_Lab.gif", bad3: "https://heroes.thelazy.net/images/4/41/Altar_of_Mana.gif"},
{question: "Click the Anti-Magic Garrison!", good1: "https://heroes.thelazy.net/images/0/0b/Anti-Magic_Garrison_%28horizontal%29.gif", bad1: "https://heroes.thelazy.net/images/9/98/Abandoned_Mine_4.gif", bad2: "https://heroes.thelazy.net/images/a/a1/Alchemist%27s_Lab.gif", bad3: "https://heroes.thelazy.net/images/4/41/Altar_of_Mana.gif"},
{question: "Click the Arena!", good1: "https://heroes.thelazy.net/images/8/80/Arena.gif", bad1: "https://heroes.thelazy.net/images/9/98/Abandoned_Mine_4.gif", bad2: "https://heroes.thelazy.net/images/a/a1/Alchemist%27s_Lab.gif", bad3: "https://heroes.thelazy.net/images/4/41/Altar_of_Mana.gif"},
{question: "Click the Black Tower!", good1: "https://heroes.thelazy.net/images/9/9d/Black_Tower_2in1.gif", bad1: "https://heroes.thelazy.net/images/9/98/Abandoned_Mine_4.gif", bad2: "https://heroes.thelazy.net/images/a/a1/Alchemist%27s_Lab.gif", bad3: "https://heroes.thelazy.net/images/4/41/Altar_of_Mana.gif"},
{question: "Click the Beholders' Sanctuary", good1: "https://heroes.thelazy.net/images/6/60/Beholders%27_Sanctuary.gif", bad1: "https://heroes.thelazy.net/images/9/98/Abandoned_Mine_4.gif", bad2: "https://heroes.thelazy.net/images/a/a1/Alchemist%27s_Lab.gif", bad3: "https://heroes.thelazy.net/images/4/41/Altar_of_Mana.gif"},
{question: "Click the Black Market!", good1: "https://heroes.thelazy.net/images/0/0c/Black_Market.gif", bad1: "https://heroes.thelazy.net/images/9/98/Abandoned_Mine_4.gif", bad2: "https://heroes.thelazy.net/images/a/a1/Alchemist%27s_Lab.gif", bad3: "https://heroes.thelazy.net/images/4/41/Altar_of_Mana.gif"},
{question: "Click the Cannon Yard!", good1: "https://heroes.thelazy.net/images/a/a9/Cannon_Yard.gif", bad1: "https://heroes.thelazy.net/images/a/a1/Alchemist%27s_Lab.gif", bad2: "https://heroes.thelazy.net/images/9/9d/Black_Tower_2in1.gif", bad3: "https://heroes.thelazy.net/images/4/41/Altar_of_Mana.gif"},
{question: "What kind of resource red dragon needs?", good1: "https://heroes.thelazy.net/images/3/33/Resource_sulfur.png", bad1: "https://heroes.thelazy.net/images/c/ca/Resource_gem.gif", bad2: "https://heroes.thelazy.net/images/6/6b/Resource_mercury.png", bad3: "https://heroes.thelazy.net/images/8/85/Resource_crystal.gif"},
{question: "What kind of resource titan needs?", good1: "https://heroes.thelazy.net/images/c/ca/Resource_gem.gif", bad1: "https://heroes.thelazy.net/images/3/33/Resource_sulfur.png", bad2: "https://heroes.thelazy.net/images/6/6b/Resource_mercury.png", bad3: "https://heroes.thelazy.net/images/8/85/Resource_crystal.gif"},
{question: "What kind of resource devil needs?", good1: "https://heroes.thelazy.net/images/6/6b/Resource_mercury.png", bad1: "https://heroes.thelazy.net/images/c/ca/Resource_gem.gif", bad2: "https://heroes.thelazy.net/images/3/33/Resource_sulfur.png", bad3: "https://heroes.thelazy.net/images/8/85/Resource_crystal.gif"},
{question: "What kind of resource green dragon needs?", good1: "https://heroes.thelazy.net/images/8/85/Resource_crystal.gif", bad1: "https://heroes.thelazy.net/images/c/ca/Resource_gem.gif", bad2: "https://heroes.thelazy.net/images/6/6b/Resource_mercury.png", bad3: "https://heroes.thelazy.net/images/3/33/Resource_sulfur.png"},
{question: "Click the Expert Luck!", good1: "https://heroes.thelazy.net/images/8/81/Expert_Luck.png", bad1: "https://heroes.thelazy.net/images/f/fd/Advanced_Luck.png", bad2: "https://heroes.thelazy.net/images/a/a4/Basic_Learning.png", bad3: "https://heroes.thelazy.net/images/7/75/Basic_Logistics.png"},
{question: "Click the Basic Luck!", good1: "https://heroes.thelazy.net/images/f/fc/Basic_Luck.png", bad1: "https://heroes.thelazy.net/images/f/fd/Advanced_Luck.png", bad2: "https://heroes.thelazy.net/images/a/a4/Basic_Learning.png", bad3: "https://heroes.thelazy.net/images/7/75/Basic_Logistics.png"},
{question: "Click the Advanced Luck!", good1: "https://heroes.thelazy.net/images/f/fd/Advanced_Luck.png", bad1: "https://heroes.thelazy.net/images/8/81/Expert_Luck.png", bad2: "https://heroes.thelazy.net/images/a/a4/Basic_Learning.png", bad3: "https://heroes.thelazy.net/images/7/75/Basic_Logistics.png"},
{question: "Click the Basic Learning!", good1: "https://heroes.thelazy.net/images/a/a4/Basic_Learning.png", bad1: "https://heroes.thelazy.net/images/f/fc/Basic_Luck.png", bad2: "https://heroes.thelazy.net/images/a/af/Advanced_Mysticism.png", bad3: "https://heroes.thelazy.net/images/7/75/Basic_Logistics.png"},
{question: "Click the Basic Logistics!", good1: "https://heroes.thelazy.net/images/7/75/Basic_Logistics.png", bad1: "https://heroes.thelazy.net/images/8/81/Expert_Luck.png", bad2: "https://heroes.thelazy.net/images/b/b9/Advanced_Logistics.png", bad3: "https://heroes.thelazy.net/images/e/e8/Expert_Logistics.png"},
{question: "Click the Advanced Logistics!", good1: "https://heroes.thelazy.net/images/b/b9/Advanced_Logistics.png", bad1: "https://heroes.thelazy.net/images/f/fc/Basic_Luck.png", bad2: "https://heroes.thelazy.net/images/a/a4/Basic_Learning.png", bad3: "https://heroes.thelazy.net/images/e/e8/Expert_Logistics.png"},
{question: "Click the Expert Logistics!", good1: "https://heroes.thelazy.net/images/e/e8/Expert_Logistics.png", bad1: "https://heroes.thelazy.net/images/8/81/Expert_Luck.png", bad2: "https://heroes.thelazy.net/images/7/75/Basic_Logistics.png", bad3: "https://heroes.thelazy.net/images/b/b9/Advanced_Logistics.png"},
{question: "Click the Basic Mysticism!", good1: "https://heroes.thelazy.net/images/1/12/Basic_Mysticism.png", bad1: "https://heroes.thelazy.net/images/f/fc/Basic_Luck.png", bad2: "https://heroes.thelazy.net/images/a/a4/Basic_Learning.png", bad3: "https://heroes.thelazy.net/images/b/b9/Advanced_Logistics.png"},
{question: "Click the Basic Navigation!", good1: "https://heroes.thelazy.net/images/f/f9/Basic_Navigation.png", bad1: "https://heroes.thelazy.net/images/8/81/Expert_Luck.png", bad2: "https://heroes.thelazy.net/images/7/75/Basic_Logistics.png", bad3: "https://heroes.thelazy.net/images/b/b9/Advanced_Logistics.png"},
{question: "Click the Advanced Navigation!", good1: "https://heroes.thelazy.net/images/b/bf/Advanced_Navigation.png", bad1: "https://heroes.thelazy.net/images/f/fc/Basic_Luck.png", bad2: "https://heroes.thelazy.net/images/a/a4/Basic_Learning.png", bad3: "https://heroes.thelazy.net/images/b/b9/Advanced_Logistics.png"},
{question: "Click the Expert Navigation!", good1: "https://heroes.thelazy.net/images/c/c0/Expert_Navigation.png", bad1: "https://heroes.thelazy.net/images/8/81/Expert_Luck.png", bad2: "https://heroes.thelazy.net/images/7/75/Basic_Logistics.png", bad3: "https://heroes.thelazy.net/images/b/b9/Advanced_Logistics.png"},
{question: "Click the Basic Necromancy!", good1: "https://heroes.thelazy.net/images/6/6b/Basic_Necromancy.png", bad1: "https://heroes.thelazy.net/images/f/fc/Basic_Luck.png", bad2: "https://heroes.thelazy.net/images/a/a4/Basic_Learning.png", bad3: "https://heroes.thelazy.net/images/b/b9/Advanced_Logistics.png"},
{question: "Click the Advanced Necromancy!", good1: "https://heroes.thelazy.net/images/7/7f/Advanced_Necromancy.png", bad1: "https://heroes.thelazy.net/images/8/81/Expert_Luck.png", bad2: "https://heroes.thelazy.net/images/7/75/Basic_Logistics.png", bad3: "https://heroes.thelazy.net/images/b/b9/Advanced_Logistics.png"},
{question: "Click the Expert Necromancy!", good1: "https://heroes.thelazy.net/images/8/8d/Expert_Necromancy.png", bad1: "https://heroes.thelazy.net/images/f/fc/Basic_Luck.png", bad2: "https://heroes.thelazy.net/images/a/a4/Basic_Learning.png", bad3: "https://heroes.thelazy.net/images/b/b9/Advanced_Logistics.png"},
{question: "Click the Basic Inteligence!", good1: "https://heroes.thelazy.net/images/8/8c/Basic_Intelligence.png", bad1: "https://heroes.thelazy.net/images/8/81/Expert_Luck.png", bad2: "https://heroes.thelazy.net/images/e/e8/Expert_Logistics.png", bad3: "https://heroes.thelazy.net/images/1/12/Basic_Mysticism.png"},
{question: "Click the Advanced Inteligence!", good1: "https://heroes.thelazy.net/images/c/c4/Advanced_Intelligence.png", bad1: "https://heroes.thelazy.net/images/f/fc/Basic_Luck.png", bad2: "https://heroes.thelazy.net/images/a/a4/Basic_Learning.png", bad3: "https://heroes.thelazy.net/images/1/12/Basic_Mysticism.png"},
{question: "Click the Expert Inteligence!", good1: "https://heroes.thelazy.net/images/d/d0/Expert_Intelligence.png", bad1: "https://heroes.thelazy.net/images/8/81/Expert_Luck.png", bad2: "https://heroes.thelazy.net/images/e/e8/Expert_Logistics.png", bad3: "https://heroes.thelazy.net/images/1/12/Basic_Mysticism.png"},
{question: "Click the Basic Diplomacy!", good1: "https://heroes.thelazy.net/images/3/38/Basic_Diplomacy.png", bad1: "https://heroes.thelazy.net/images/f/fc/Basic_Luck.png", bad2: "https://heroes.thelazy.net/images/a/a4/Basic_Learning.png", bad3: "https://heroes.thelazy.net/images/1/12/Basic_Mysticism.png"},
{question: "Click the Advanced Diplomacy!", good1: "https://heroes.thelazy.net/images/4/43/Advanced_Diplomacy.png", bad1: "https://heroes.thelazy.net/images/8/81/Expert_Luck.png", bad2: "https://heroes.thelazy.net/images/e/e8/Expert_Logistics.png", bad3: "https://heroes.thelazy.net/images/1/12/Basic_Mysticism.png"},
{question: "Click the Expert Diplomacy", good1: "https://heroes.thelazy.net/images/6/60/Expert_Diplomacy.png", bad1: "https://heroes.thelazy.net/images/f/fc/Basic_Luck.png", bad2: "https://heroes.thelazy.net/images/a/a4/Basic_Learning.png", bad3: "https://heroes.thelazy.net/images/1/12/Basic_Mysticism.png"},
{question: "Click the Expert Mysticism!", good1: "https://heroes.thelazy.net/images/7/79/Expert_Mysticism.png", bad1: "https://heroes.thelazy.net/images/8/81/Expert_Luck.png", bad2: "https://heroes.thelazy.net/images/e/e8/Expert_Logistics.png", bad3: "https://heroes.thelazy.net/images/1/12/Basic_Mysticism.png"},
{question: "Click the Advanced Mysticism!", good1: "https://heroes.thelazy.net/images/a/af/Advanced_Mysticism.png", bad1: "https://heroes.thelazy.net/images/f/fc/Basic_Luck.png", bad2: "https://heroes.thelazy.net/images/a/a4/Basic_Learning.png", bad3: "https://heroes.thelazy.net/images/1/12/Basic_Mysticism.png"},
{question: "Click the Castle puzzle!", good1: "https://heroes.thelazy.net/images/3/3a/Puzzle_map_castle.gif", bad1: "https://heroes.thelazy.net/images/f/fb/Puzzle_map_inferno.gif", bad2: "https://heroes.thelazy.net/images/d/db/Puzzle_map_tower.gif", bad3: "https://heroes.thelazy.net/images/0/04/Puzzle_map_necropolis.gif"},
{question: "Click the Inferno puzzle!", good1: "https://heroes.thelazy.net/images/f/fb/Puzzle_map_inferno.gif", bad1: "https://heroes.thelazy.net/images/3/3a/Puzzle_map_castle.gif", bad2: "https://heroes.thelazy.net/images/d/db/Puzzle_map_tower.gif", bad3: "https://heroes.thelazy.net/images/0/04/Puzzle_map_necropolis.gif"},
{question: "Click the Necropolis puzzle!", good1: "https://heroes.thelazy.net/images/0/04/Puzzle_map_necropolis.gif", bad1: "https://heroes.thelazy.net/images/3/3a/Puzzle_map_castle.gif", bad2: "https://heroes.thelazy.net/images/f/fb/Puzzle_map_inferno.gif", bad3: "https://heroes.thelazy.net/images/6/6d/Puzzle_map_rampart.gif"},
{question: "Click the Rampart puzzle!", good1: "https://heroes.thelazy.net/images/6/6d/Puzzle_map_rampart.gif", bad1: "https://heroes.thelazy.net/images/3/3a/Puzzle_map_castle.gif", bad2: "https://heroes.thelazy.net/images/f/fb/Puzzle_map_inferno.gif", bad3: "https://heroes.thelazy.net/images/0/04/Puzzle_map_necropolis.gif"},
{question: "Click the Tower puzzle!", good1: "https://heroes.thelazy.net/images/d/db/Puzzle_map_tower.gif", bad1: "https://heroes.thelazy.net/images/3/3a/Puzzle_map_castle.gif", bad2: "https://heroes.thelazy.net/images/f/fb/Puzzle_map_inferno.gif", bad3: "https://heroes.thelazy.net/images/0/04/Puzzle_map_necropolis.gif"},
{question: "Click the Dungeon puzzle!", good1: "https://heroes.thelazy.net/images/7/76/Puzzle_map_dungeon.gif", bad1: "https://heroes.thelazy.net/images/3/3a/Puzzle_map_castle.gif", bad2: "https://heroes.thelazy.net/images/f/fb/Puzzle_map_inferno.gif", bad3: "https://heroes.thelazy.net/images/0/04/Puzzle_map_necropolis.gif"},
{question: "Click the Stronghold puzzle!", good1: "https://heroes.thelazy.net/images/7/7d/Puzzle_map_stronghold.gif", bad1: "https://heroes.thelazy.net/images/3/3a/Puzzle_map_castle.gif", bad2: "https://heroes.thelazy.net/images/f/fb/Puzzle_map_inferno.gif", bad3: "https://heroes.thelazy.net/images/0/04/Puzzle_map_necropolis.gif"},
{question: "Click the Fortress puzzle!", good1: "https://heroes.thelazy.net/images/9/97/Puzzle_map_fortress.gif", bad1: "https://heroes.thelazy.net/images/3/3a/Puzzle_map_castle.gif", bad2: "https://heroes.thelazy.net/images/f/fb/Puzzle_map_inferno.gif", bad3: "https://heroes.thelazy.net/images/0/04/Puzzle_map_necropolis.gif"},
{question: "Click the Conflux puzzle!", good1: "https://heroes.thelazy.net/images/b/bd/Puzzle_map_conflux.gif", bad1: "https://heroes.thelazy.net/images/3/3a/Puzzle_map_castle.gif", bad2: "https://heroes.thelazy.net/images/f/fb/Puzzle_map_inferno.gif", bad3: "https://heroes.thelazy.net/images/0/04/Puzzle_map_necropolis.gif"},
{question: "Click the Cove puzzle!", good1: "https://heroes.thelazy.net/images/0/08/Puzzle_map_cove.gif", bad1: "https://heroes.thelazy.net/images/3/3a/Puzzle_map_castle.gif", bad2: "https://heroes.thelazy.net/images/f/fb/Puzzle_map_inferno.gif", bad3: "https://heroes.thelazy.net/images/0/04/Puzzle_map_necropolis.gif"},
{question: "Select the one with +1 luck.", good1: "https://heroes.thelazy.net/images/5/5f/Artifact_Clover_of_Fortune.gif", bad1: "https://heroes.thelazy.net/images/1/15/Artifact_Badge_of_Courage.gif", bad2: "https://heroes.thelazy.net/images/5/5a/Artifact_Crest_of_Valor.gif", bad3: "https://heroes.thelazy.net/images/4/41/Artifact_Glyph_of_Gallantry.gif"},
{question: "Select the one with +1 luck.", good1: "https://heroes.thelazy.net/images/4/43/Artifact_Ladybird_of_Luck.gif", bad1: "https://heroes.thelazy.net/images/1/15/Artifact_Badge_of_Courage.gif", bad2: "https://heroes.thelazy.net/images/5/5a/Artifact_Crest_of_Valor.gif", bad3: "https://heroes.thelazy.net/images/4/41/Artifact_Glyph_of_Gallantry.gif"},
{question: "Select the one with +1 luck.", good1: "https://heroes.thelazy.net/images/5/5d/Artifact_Cards_of_Prophecy.gif", bad1: "https://heroes.thelazy.net/images/1/15/Artifact_Badge_of_Courage.gif", bad2: "https://heroes.thelazy.net/images/5/5a/Artifact_Crest_of_Valor.gif", bad3: "https://heroes.thelazy.net/images/4/41/Artifact_Glyph_of_Gallantry.gif"},
{question: "Select the one with +1 morale.", good1: "https://heroes.thelazy.net/images/4/41/Artifact_Glyph_of_Gallantry.gif", bad1: "https://heroes.thelazy.net/images/5/5d/Artifact_Cards_of_Prophecy.gif", bad2: "https://heroes.thelazy.net/images/4/43/Artifact_Ladybird_of_Luck.gif", bad3: "https://heroes.thelazy.net/images/5/5f/Artifact_Clover_of_Fortune.gif"},
{question: "Select the one with +1 morale.", good1: "https://heroes.thelazy.net/images/5/5a/Artifact_Crest_of_Valor.gif", bad1: "https://heroes.thelazy.net/images/5/5d/Artifact_Cards_of_Prophecy.gif", bad2: "https://heroes.thelazy.net/images/4/43/Artifact_Ladybird_of_Luck.gif", bad3: "https://heroes.thelazy.net/images/5/5f/Artifact_Clover_of_Fortune.gif"},
{question: "Select the one with +1 morale.", good1: "https://heroes.thelazy.net/images/1/15/Artifact_Badge_of_Courage.gif", bad1: "https://heroes.thelazy.net/images/5/5d/Artifact_Cards_of_Prophecy.gif", bad2: "https://heroes.thelazy.net/images/4/43/Artifact_Ladybird_of_Luck.gif", bad3: "https://heroes.thelazy.net/images/5/5f/Artifact_Clover_of_Fortune.gif"},
{question: "Select the one with +1 scouting radius.", good1: "https://heroes.thelazy.net/images/5/51/Artifact_Spyglass.gif", bad1: "https://heroes.thelazy.net/images/5/5d/Artifact_Cards_of_Prophecy.gif", bad2: "https://heroes.thelazy.net/images/4/43/Artifact_Ladybird_of_Luck.gif", bad3: "https://heroes.thelazy.net/images/5/5f/Artifact_Clover_of_Fortune.gif"},
{question: "Select the one with +1 scouting radius.", good1: "https://heroes.thelazy.net/images/0/0a/Artifact_Speculum.gif", bad1: "https://heroes.thelazy.net/images/5/5d/Artifact_Cards_of_Prophecy.gif", bad2: "https://heroes.thelazy.net/images/4/43/Artifact_Ladybird_of_Luck.gif", bad3: "https://heroes.thelazy.net/images/5/5f/Artifact_Clover_of_Fortune.gif"},
{question: "Select the one with berserk immunity.", good1: "https://heroes.thelazy.net/images/6/6e/Artifact_Pendant_of_Dispassion.gif", bad1: "https://heroes.thelazy.net/images/5/5d/Artifact_Cards_of_Prophecy.gif", bad2: "https://heroes.thelazy.net/images/4/43/Artifact_Ladybird_of_Luck.gif", bad3: "https://heroes.thelazy.net/images/5/5f/Artifact_Clover_of_Fortune.gif"},
{question: "Select the one with hypnotize immunity.", good1: "https://heroes.thelazy.net/images/6/69/Artifact_Pendant_of_Free_Will.gif", bad1: "https://heroes.thelazy.net/images/5/5d/Artifact_Cards_of_Prophecy.gif", bad2: "https://heroes.thelazy.net/images/4/43/Artifact_Ladybird_of_Luck.gif", bad3: "https://heroes.thelazy.net/images/5/5f/Artifact_Clover_of_Fortune.gif"},
{question: "Kill the one with laziest creature design! 😪", good1: "https://heroes.thelazy.net/images/a/a2/SteelgolemStill.gif", bad1: "https://heroes.thelazy.net/images/1/11/Creature_Skeleton.gif", bad2: "https://heroes.thelazy.net/images/9/9a/Creature_Sprite.gif", bad3: "https://heroes.thelazy.net/images/9/93/Creature_Behemoth.gif"},
{question: "Kill the one with fur color of dirrhea! 💩", good1: "https://heroes.thelazy.net/images/9/93/Creature_Behemoth.gif", bad1: "https://heroes.thelazy.net/images/1/11/Creature_Skeleton.gif", bad2: "https://heroes.thelazy.net/images/9/9a/Creature_Sprite.gif", bad3: "https://heroes.thelazy.net/images/a/a2/SteelgolemStill.gif"},
{question: "Kill the one with two arg⭕️⭕️ments!", good1: "https://heroes.thelazy.net/images/9/9a/Creature_Sprite.gif", bad1: "https://heroes.thelazy.net/images/3/3e/Creature_Leprechaun.gif", bad2: "https://heroes.thelazy.net/images/1/11/Creature_Skeleton.gif", bad3: "https://heroes.thelazy.net/images/9/93/Creature_Behemoth.gif"},
{question: "Kill the one with spooks! 🦴", good1: "https://heroes.thelazy.net/images/1/11/Creature_Skeleton.gif", bad1: "https://heroes.thelazy.net/images/3/3e/Creature_Leprechaun.gif", bad2: "https://heroes.thelazy.net/images/9/9a/Creature_Sprite.gif", bad3: "https://heroes.thelazy.net/images/a/a2/SteelgolemStill.gif"},
{question: "Kill the GINGER! 👹", good1: "https://heroes.thelazy.net/images/3/3e/Creature_Leprechaun.gif", bad1: "https://heroes.thelazy.net/images/5/52/Creature_Evil_Eye.gif", bad2: "https://heroes.thelazy.net/images/6/66/Creature_Crystal_dragon.gif", bad3: "https://heroes.thelazy.net/images/9/93/Creature_Behemoth.gif"},
{question: "Kill the one with crystal dirrhea! 💩", good1: "https://heroes.thelazy.net/images/6/66/Creature_Crystal_dragon.gif", bad1: "https://heroes.thelazy.net/images/3/3e/Creature_Leprechaun.gif", bad2: "https://heroes.thelazy.net/images/9/9a/Creature_Sprite.gif", bad3: "https://heroes.thelazy.net/images/a/a2/SteelgolemStill.gif"},
{question: "Kill the one with laser contacts! 👁", good1: "https://heroes.thelazy.net/images/5/52/Creature_Evil_Eye.gif", bad1: "https://heroes.thelazy.net/images/6/66/Creature_Crystal_dragon.gif", bad2: "https://heroes.thelazy.net/images/3/3e/Creature_Leprechaun.gif", bad3: "https://heroes.thelazy.net/images/9/93/Creature_Behemoth.gif"},
{question: "Kill the one with most hentai roles! 🐙", good1: "https://heroes.thelazy.net/images/8/89/Creature_Fangarm.gif", bad1: "https://heroes.thelazy.net/images/3/3e/Creature_Leprechaun.gif", bad2: "https://heroes.thelazy.net/images/9/9a/Creature_Sprite.gif", bad3: "https://heroes.thelazy.net/images/a/a2/SteelgolemStill.gif"},
{question: "Kill the one that can give you ANYTHING! 🙈", good1: "https://heroes.thelazy.net/images/1/1a/Creature_Master_Genie.gif", bad1: "https://heroes.thelazy.net/images/6/66/Creature_Crystal_dragon.gif", bad2: "https://heroes.thelazy.net/images/3/3e/Creature_Leprechaun.gif", bad3: "https://heroes.thelazy.net/images/9/93/Creature_Behemoth.gif"},
{question: "Kill the one with ability to give multiple handjobs! 💦", good1: "https://heroes.thelazy.net/images/5/52/Creature_Naga.gif", bad1: "https://heroes.thelazy.net/images/3/3e/Creature_Leprechaun.gif", bad2: "https://heroes.thelazy.net/images/9/9a/Creature_Sprite.gif", bad3: "https://heroes.thelazy.net/images/a/a2/SteelgolemStill.gif"},
{question: "Which hero has the speciality of attack?", good1: "https://heroes.thelazy.net/images/7/7e/Hero_Crag_Hack.png", bad1: "https://heroes.thelazy.net/images/f/fb/Hero_Jabarkas.png", bad2: "https://heroes.thelazy.net/images/9/9d/Hero_Gurnisson.png", bad3: "https://heroes.thelazy.net/images/4/48/Hero_Gretchin.png"},
{question: "Which hero has the speciality of goblins?", good1: "https://heroes.thelazy.net/images/4/48/Hero_Gretchin.png", bad1: "https://heroes.thelazy.net/images/f/fb/Hero_Jabarkas.png", bad2: "https://heroes.thelazy.net/images/9/9d/Hero_Gurnisson.png", bad3: "https://heroes.thelazy.net/images/7/7e/Hero_Crag_Hack.png"},
{question: "Which hero has the speciality of balista?", good1: "https://heroes.thelazy.net/images/9/9d/Hero_Gurnisson.png", bad1: "https://heroes.thelazy.net/images/f/fb/Hero_Jabarkas.png", bad2: "https://heroes.thelazy.net/images/4/48/Hero_Gretchin.png", bad3: "https://heroes.thelazy.net/images/7/7e/Hero_Crag_Hack.png"},
{question: "Which hero has the speciality of orcs?", good1: "https://heroes.thelazy.net/images/f/fb/Hero_Jabarkas.png", bad1: "https://heroes.thelazy.net/images/9/9d/Hero_Gurnisson.png", bad2: "https://heroes.thelazy.net/images/4/48/Hero_Gretchin.png", bad3: "https://heroes.thelazy.net/images/7/7e/Hero_Crag_Hack.png"},
{question: "Which hero has the speciality of ogres?", good1: "https://heroes.thelazy.net/images/f/f9/Hero_Krellion.png", bad1: "https://heroes.thelazy.net/images/9/9d/Hero_Gurnisson.png", bad2: "https://heroes.thelazy.net/images/4/48/Hero_Gretchin.png", bad3: "https://heroes.thelazy.net/images/7/7e/Hero_Crag_Hack.png"},
{question: "Which hero has the speciality of rocs?", good1: "https://heroes.thelazy.net/images/5/5d/Hero_Shiva.png", bad1: "https://heroes.thelazy.net/images/9/9d/Hero_Gurnisson.png", bad2: "https://heroes.thelazy.net/images/4/48/Hero_Gretchin.png", bad3: "https://heroes.thelazy.net/images/7/7e/Hero_Crag_Hack.png"},
{question: "Which hero has the speciality of wolf riders?", good1: "https://heroes.thelazy.net/images/a/ac/Hero_Tyraxor.png", bad1: "https://heroes.thelazy.net/images/9/9d/Hero_Gurnisson.png", bad2: "https://heroes.thelazy.net/images/4/48/Hero_Gretchin.png", bad3: "https://heroes.thelazy.net/images/7/7e/Hero_Crag_Hack.png"},
{question: "Which hero has the speciality of cyclops?", good1: "https://heroes.thelazy.net/images/3/39/Hero_Yog.png", bad1: "https://heroes.thelazy.net/images/9/9d/Hero_Gurnisson.png", bad2: "https://heroes.thelazy.net/images/4/48/Hero_Gretchin.png", bad3: "https://heroes.thelazy.net/images/7/7e/Hero_Crag_Hack.png"},
{question: "Which hero has the speciality of ogres?", good1: "https://heroes.thelazy.net/images/7/72/Hero_Boragus.png", bad1: "https://heroes.thelazy.net/images/9/9d/Hero_Gurnisson.png", bad2: "https://heroes.thelazy.net/images/4/48/Hero_Gretchin.png", bad3: "https://heroes.thelazy.net/images/7/7e/Hero_Crag_Hack.png"},
{question: "Which hero has the speciality of behemots?", good1: "https://heroes.thelazy.net/images/2/2b/Hero_Kilgor.png", bad1: "https://heroes.thelazy.net/images/9/9d/Hero_Gurnisson.png", bad2: "https://heroes.thelazy.net/images/4/48/Hero_Gretchin.png", bad3: "https://heroes.thelazy.net/images/7/7e/Hero_Crag_Hack.png"},
{question: "Which hero has the speciality of logistics?", good1: "https://heroes.thelazy.net/images/c/c9/Hero_Dessa.png", bad1: "https://heroes.thelazy.net/images/9/9d/Hero_Gurnisson.png", bad2: "https://heroes.thelazy.net/images/4/48/Hero_Gretchin.png", bad3: "https://heroes.thelazy.net/images/7/7e/Hero_Crag_Hack.png"},
{question: "Which hero has the speciality of sorcery?", good1: "https://heroes.thelazy.net/images/8/8b/Hero_Gird.png", bad1: "https://heroes.thelazy.net/images/9/9d/Hero_Gurnisson.png", bad2: "https://heroes.thelazy.net/images/4/48/Hero_Gretchin.png", bad3: "https://heroes.thelazy.net/images/7/7e/Hero_Crag_Hack.png"},
{question: "Which hero has the speciality of offense?", good1: "https://heroes.thelazy.net/images/e/ea/Hero_Gundula.png", bad1: "https://heroes.thelazy.net/images/9/9d/Hero_Gurnisson.png", bad2: "https://heroes.thelazy.net/images/4/48/Hero_Gretchin.png", bad3: "https://heroes.thelazy.net/images/7/7e/Hero_Crag_Hack.png"},
{question: "Which hero has the speciality of eagle eye?", good1: "https://heroes.thelazy.net/images/3/3a/Hero_Oris.png", bad1: "https://heroes.thelazy.net/images/9/9d/Hero_Gurnisson.png", bad2: "https://heroes.thelazy.net/images/4/48/Hero_Gretchin.png", bad3: "https://heroes.thelazy.net/images/7/7e/Hero_Crag_Hack.png"},
{question: "Which hero has the speciality of gems?", good1: "https://heroes.thelazy.net/images/d/d7/Hero_Saurug.png", bad1: "https://heroes.thelazy.net/images/9/9d/Hero_Gurnisson.png", bad2: "https://heroes.thelazy.net/images/4/48/Hero_Gretchin.png", bad3: "https://heroes.thelazy.net/images/7/7e/Hero_Crag_Hack.png"},
{question: "Which hero has the speciality of haste?", good1: "https://heroes.thelazy.net/images/3/3f/Hero_Terek.png", bad1: "https://heroes.thelazy.net/images/9/9d/Hero_Gurnisson.png", bad2: "https://heroes.thelazy.net/images/4/48/Hero_Gretchin.png", bad3: "https://heroes.thelazy.net/images/7/7e/Hero_Crag_Hack.png"},
{question: "Which hero has the speciality of ogres?", good1: "https://heroes.thelazy.net/images/3/31/Hero_Vey.png", bad1: "https://heroes.thelazy.net/images/9/9d/Hero_Gurnisson.png", bad2: "https://heroes.thelazy.net/images/4/48/Hero_Gretchin.png", bad3: "https://heroes.thelazy.net/images/7/7e/Hero_Crag_Hack.png"},
{question: "Which hero has the speciality of precision?", good1: "https://heroes.thelazy.net/images/9/92/Hero_Zubin.png", bad1: "https://heroes.thelazy.net/images/9/9d/Hero_Gurnisson.png", bad2: "https://heroes.thelazy.net/images/4/48/Hero_Gretchin.png", bad3: "https://heroes.thelazy.net/images/7/7e/Hero_Crag_Hack.png"},
{question: "Which city has Guardhouse?", good1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Archers' Tower?", good1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Griffin Tower?", good1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Barracks?", good1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Monastery?", good1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Training Grounds?", good1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Portal Of Glory?", good1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Angels?", good1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has A R C H E R S?", good1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Swordsmans?", good1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Archers?", good1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Zealots?", good1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Centaurs?", good1: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Dwarves?", good1: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Elves?", good1: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Dendroids?", good1: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Green Dragons?", good1: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Pegasuses?", good1: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Unicorns?", good1: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Miners' Guild?", good1: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Mystic Pond?", good1: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Treasury?", good1: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Fountain Of Fortune?", good1: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has Dragon Cliffs?", good1: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad1: "https://heroes.thelazy.net/images/f/f9/Adventure_Map_Conflux_fort.gif", bad2: "https://heroes.thelazy.net/images/2/24/Adventure_Map_Fortress_fort.gif", bad3: "https://heroes.thelazy.net/images/f/fe/Adventure_Map_Cove_fort_%28HotA%29.gif"},
{question: "Which city has goblins?", good1: "https://heroes.thelazy.net/images/8/83/Adventure_Map_Stronghold_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has orcs?", good1: "https://heroes.thelazy.net/images/8/83/Adventure_Map_Stronghold_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has wolf riders?", good1: "https://heroes.thelazy.net/images/8/83/Adventure_Map_Stronghold_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has ogres?", good1: "https://heroes.thelazy.net/images/8/83/Adventure_Map_Stronghold_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has rocs?", good1: "https://heroes.thelazy.net/images/8/83/Adventure_Map_Stronghold_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has behemoths?", good1: "https://heroes.thelazy.net/images/8/83/Adventure_Map_Stronghold_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has cyclops?", good1: "https://heroes.thelazy.net/images/8/83/Adventure_Map_Stronghold_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has harpies?", good1: "https://heroes.thelazy.net/images/9/91/Adventure_Map_Dungeon_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has blind cucumbers? 🥒", good1: "https://heroes.thelazy.net/images/9/91/Adventure_Map_Dungeon_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has tentacle eyes?", good1: "https://heroes.thelazy.net/images/9/91/Adventure_Map_Dungeon_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has red dragons?", good1: "https://heroes.thelazy.net/images/9/91/Adventure_Map_Dungeon_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has manticores?", good1: "https://heroes.thelazy.net/images/9/91/Adventure_Map_Dungeon_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has minotaurs?", good1: "https://heroes.thelazy.net/images/9/91/Adventure_Map_Dungeon_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has nagas?", good1: "https://heroes.thelazy.net/images/9/91/Adventure_Map_Dungeon_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has skeletons?", good1: "https://heroes.thelazy.net/images/3/32/Adventure_Map_Necropolis_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has zombies?", good1: "https://heroes.thelazy.net/images/3/32/Adventure_Map_Necropolis_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has liches?", good1: "https://heroes.thelazy.net/images/3/32/Adventure_Map_Necropolis_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has dark knights?", good1: "https://heroes.thelazy.net/images/3/32/Adventure_Map_Necropolis_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has bone(r) dragons?", good1: "https://heroes.thelazy.net/images/3/32/Adventure_Map_Necropolis_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has vamipres?", good1: "https://heroes.thelazy.net/images/3/32/Adventure_Map_Necropolis_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has 🧛‍♂️?", good1: "https://heroes.thelazy.net/images/3/32/Adventure_Map_Necropolis_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has 🧟‍♂️?", good1: "https://heroes.thelazy.net/images/3/32/Adventure_Map_Necropolis_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has 🦴?", good1: "https://heroes.thelazy.net/images/3/32/Adventure_Map_Necropolis_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has 👹?", good1: "https://heroes.thelazy.net/images/8/84/Adventure_Map_Inferno_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has imps?", good1: "https://heroes.thelazy.net/images/8/84/Adventure_Map_Inferno_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has familiars?", good1: "https://heroes.thelazy.net/images/8/84/Adventure_Map_Inferno_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has gogs?", good1: "https://heroes.thelazy.net/images/8/84/Adventure_Map_Inferno_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has cerberuses?", good1: "https://heroes.thelazy.net/images/8/84/Adventure_Map_Inferno_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has devils?", good1: "https://heroes.thelazy.net/images/8/84/Adventure_Map_Inferno_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has pit lords?", good1: "https://heroes.thelazy.net/images/8/84/Adventure_Map_Inferno_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has hell hounds?", good1: "https://heroes.thelazy.net/images/8/84/Adventure_Map_Inferno_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has efreets?", good1: "https://heroes.thelazy.net/images/8/84/Adventure_Map_Inferno_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has magogs?", good1: "https://heroes.thelazy.net/images/8/84/Adventure_Map_Inferno_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has 😈?", good1: "https://heroes.thelazy.net/images/8/84/Adventure_Map_Inferno_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which city has 👿?", good1: "https://heroes.thelazy.net/images/8/84/Adventure_Map_Inferno_fort.gif", bad1: "https://heroes.thelazy.net/images/4/42/Adventure_Map_Castle_fort.gif", bad2: "https://heroes.thelazy.net/images/0/0e/Adventure_Map_Rampart_fort.gif", bad3: "https://heroes.thelazy.net/images/d/dd/Adventure_Map_Tower_fort.gif"},
{question: "Which ", good1: "", bad1: "", bad2: "", bad3: ""}];

// {question: "", good1: "", bad1: "", bad2: "", bad3: ""}